#!/usr/bin/env bash

bookmark="$(xclip -o)"

file='/home/dylan/.config/bookmarks/list'
if  grep -q "^$bookmark$" "$file"; then
        notify-send -t 2000 "Bookmark existe déja" 
else
         notify-send -t 2000 "Bookmark $bookmark sauvegardé" 
         echo "$bookmark" >> "$file" 
fi

