-- local parser_config = require("nvim-treesitter.parsers").get_parser_configs()
-- parser_config.powershell = {
-- 	install_info = {
-- 		url = "C:\\temp\\",
-- 		files = { "src/parser.c" },
-- 		branch = "main",
-- 		generate_requires_npm = false,
-- 		requires_generate_from_grammar = false,
-- 	},
-- 	filetype = "ps1",
-- 	used_by = { "powershell", "ps1" },
-- }
