[[language]]
name = "powershell"
scope = "source.ps1"
file-types = ["ps1", "psm1"]
roots = [".git"]
comment-token = "#"
indent = { tab-width = 4, unit = "    " }
language-servers = [ "powershell-editor-services" ]

[language-server.powershell-editor-services]
command = "pwsh" 
args = [ "-NoLogo", "-NoProfile", "-Command", "C:\\Users\\dylan\\AppData\\Local\\nvim-data\\mason\\packages\\powershell-editor-services\\PowerShellEditorServices\\Start-EditorServices.ps1", "-BundledModulesPath", "C:\\Users\\dylan\\AppData\\Local\\nvim-data\\mason\\packages\\powershell-editor-services", "-SessionDetailsPath", "C:\\Users\\dylan\\AppData\\Local\\Temp\\nvim\\powershell_es.session.json", "-LogPath", "C:\\Users\\dylan\\AppData\\Local\\Temp\\nvim\\powershell_es.log", "-FeatureFlags", "@()", "-AdditionalModules", "@()", "-HostName", "nvim", "-HostProfileId", "0", "-HostVersion", "1.0.0", "-Stdio", "-LogLevel", "Normal" ]
