environments:
  home:
    - obsidian.desktop
    - org.wezfurlong.wezterm.desktop
    - org.keepassxc.KeePassXC.desktop
    - firefox.desktop
    - discord.desktop
    - thunderbird.desktop
    - element-desktop.desktop
    - todoist.desktop

  work:
    - firefox.desktop
    - discord.desktop
    - thunderbird.desktop
    - org.remmina.Remmina.desktop
    - linphone.desktop
    - microsoft-edge.desktop
    - todoist.desktop
