local wezterm = require("wezterm")

wezterm.font_with_fallback {
  'Fira Code',
  'DengXian',
}

return {
	color_scheme = "Catppuccin Macchiato",
	-- font = wezterm.font("Fira Code Nerd Font"),
	font_size = 13.0,
	hide_tab_bar_if_only_one_tab = true,
	default_prog = { "pwsh.exe" },
  -- default_prog = {"wsl.exe"},
	-- font_dirs = { "fonts", "C:\\windows\\fonts" },
  -- -- Enable logging
  enable_wayland = false,
  -- log_to_file = true,
  -- debug_key_events = true,

  -- Leader is the same as my old tmux prefix
leader = { key = 'Space', mods = 'CTRL', timeout_milliseconds = 1000 },

	keys = {

  {
    mods   = "LEADER",
    key    = "-",
    action = wezterm.action.SplitVertical { domain = 'CurrentPaneDomain' }
  },
  {
    mods   = "LEADER",
    key    = "=",
    action = wezterm.action.SplitHorizontal { domain = 'CurrentPaneDomain' }
  },



		{ key = "Tab", mods = "CTRL", action = wezterm.action.ActivateTabRelative(1) },
		{ key = "Tab", mods = "SHIFT|CTRL", action = wezterm.action.ActivateTabRelative(-1) },
		-- { key = 'Enter', mods = 'ALT', action =wezterm.action.ToggleFullScreen },
		{ key = "!", mods = "CTRL", action = wezterm.action.ActivateTab(0) },
		{ key = "!", mods = "SHIFT|CTRL", action = wezterm.action.ActivateTab(0) },
		{ key = '"', mods = "ALT|CTRL", action = wezterm.action.SplitVertical({ domain = "CurrentPaneDomain" }) },
		{ key = '"', mods = "SHIFT|ALT|CTRL", action = wezterm.action.SplitVertical({ domain = "CurrentPaneDomain" }) },
		{ key = "#", mods = "CTRL", action = wezterm.action.ActivateTab(2) },
		{ key = "#", mods = "SHIFT|CTRL", action = wezterm.action.ActivateTab(2) },
		{ key = "$", mods = "CTRL", action = wezterm.action.ActivateTab(3) },
		{ key = "$", mods = "SHIFT|CTRL", action = wezterm.action.ActivateTab(3) },
		{ key = "%", mods = "CTRL", action = wezterm.action.ActivateTab(4) },
		{ key = "%", mods = "SHIFT|CTRL", action = wezterm.action.ActivateTab(4) },
		{ key = "%", mods = "ALT|CTRL", action = wezterm.action.SplitHorizontal({ domain = "CurrentPaneDomain" }) },
		{
			key = "%",
			mods = "SHIFT|ALT|CTRL",
			action = wezterm.action.SplitHorizontal({ domain = "CurrentPaneDomain" }),
		},
		{ key = "&", mods = "CTRL", action = wezterm.action.ActivateTab(6) },
		{ key = "&", mods = "SHIFT|CTRL", action = wezterm.action.ActivateTab(6) },
		{ key = "'", mods = "SHIFT|ALT|CTRL", action = wezterm.action.SplitVertical({ domain = "CurrentPaneDomain" }) },
		{ key = "(", mods = "CTRL", action = wezterm.action.ActivateTab(-1) },
		{ key = "(", mods = "SHIFT|CTRL", action = wezterm.action.ActivateTab(-1) },
		{ key = ")", mods = "CTRL", action = wezterm.action.ResetFontSize },
		{ key = ")", mods = "SHIFT|CTRL", action = wezterm.action.ResetFontSize },
		{ key = "*", mods = "CTRL", action = wezterm.action.ActivateTab(7) },
		{ key = "*", mods = "SHIFT|CTRL", action = wezterm.action.ActivateTab(7) },
		{ key = "+", mods = "CTRL", action = wezterm.action.IncreaseFontSize },
		{ key = "+", mods = "SHIFT|CTRL", action = wezterm.action.IncreaseFontSize },
		{ key = "-", mods = "CTRL", action = wezterm.action.DecreaseFontSize },
		{ key = "-", mods = "SHIFT|CTRL", action = wezterm.action.DecreaseFontSize },
		{ key = "-", mods = "SUPER", action = wezterm.action.DecreaseFontSize },
		{ key = "0", mods = "CTRL", action = wezterm.action.ResetFontSize },

		{ key = "0", mods = "SHIFT|CTRL", action = wezterm.action.ResetFontSize },
		{ key = "0", mods = "SUPER", action = wezterm.action.ResetFontSize },
		{ key = "1", mods = "SHIFT|CTRL", action = wezterm.action.ActivateTab(0) },
		{ key = "1", mods = "SUPER", action = wezterm.action.ActivateTab(0) },
		{ key = "2", mods = "SHIFT|CTRL", action = wezterm.action.ActivateTab(1) },
		{ key = "2", mods = "SUPER", action = wezterm.action.ActivateTab(1) },
		{ key = "3", mods = "SHIFT|CTRL", action = wezterm.action.ActivateTab(2) },
		{ key = "3", mods = "SUPER", action = wezterm.action.ActivateTab(2) },
		{ key = "4", mods = "SHIFT|CTRL", action = wezterm.action.ActivateTab(3) },
		{ key = "4", mods = "SUPER", action = wezterm.action.ActivateTab(3) },
		{ key = "5", mods = "SHIFT|CTRL", action = wezterm.action.ActivateTab(4) },
		{
			key = "5",
			mods = "SHIFT|ALT|CTRL",
			action = wezterm.action.SplitHorizontal({ domain = "CurrentPaneDomain" }),
		},
		{ key = "5", mods = "SUPER", action = wezterm.action.ActivateTab(4) },
		{ key = "6", mods = "SHIFT|CTRL", action = wezterm.action.ActivateTab(5) },
		{ key = "6", mods = "SUPER", action = wezterm.action.ActivateTab(5) },
		{ key = "7", mods = "SHIFT|CTRL", action = wezterm.action.ActivateTab(6) },
		{ key = "7", mods = "SUPER", action = wezterm.action.ActivateTab(6) },
		{ key = "8", mods = "SHIFT|CTRL", action = wezterm.action.ActivateTab(7) },
		{ key = "8", mods = "SUPER", action = wezterm.action.ActivateTab(7) },
		{ key = "9", mods = "SHIFT|CTRL", action = wezterm.action.ActivateTab(-1) },
		{ key = "9", mods = "SUPER", action = wezterm.action.ActivateTab(-1) },
		{ key = "=", mods = "CTRL", action = wezterm.action.IncreaseFontSize },
		{ key = "=", mods = "SHIFT|CTRL", action = wezterm.action.IncreaseFontSize },
		{ key = "=", mods = "SUPER", action = wezterm.action.IncreaseFontSize },
		{ key = "@", mods = "CTRL", action = wezterm.action.ActivateTab(1) },
		{ key = "@", mods = "SHIFT|CTRL", action = wezterm.action.ActivateTab(1) },
		{ key = "C", mods = "CTRL", action = wezterm.action.CopyTo("Clipboard") },
		{ key = "C", mods = "SHIFT|CTRL", action = wezterm.action.CopyTo("Clipboard") },
		{ key = "F", mods = "CTRL", action = wezterm.action.Search("CurrentSelectionOrEmptyString") },
		{ key = "F", mods = "SHIFT|CTRL", action = wezterm.action.Search("CurrentSelectionOrEmptyString") },
		{ key = "K", mods = "CTRL", action = wezterm.action.ClearScrollback("ScrollbackOnly") },
		{ key = "K", mods = "SHIFT|CTRL", action = wezterm.action.ClearScrollback("ScrollbackOnly") },
		{ key = "L", mods = "CTRL", action = wezterm.action.ShowDebugOverlay },
		{ key = "L", mods = "SHIFT|CTRL", action = wezterm.action.ShowDebugOverlay },
		{ key = "M", mods = "CTRL", action = wezterm.action.Hide },
		{ key = "M", mods = "SHIFT|CTRL", action = wezterm.action.Hide },
		{ key = "N", mods = "CTRL", action = wezterm.action.SpawnWindow },
		{ key = "N", mods = "SHIFT|CTRL", action = wezterm.action.SpawnWindow },
		{ key = "P", mods = "CTRL", action = wezterm.action.ActivateCommandPalette },
		{ key = "P", mods = "SHIFT|CTRL", action = wezterm.action.ActivateCommandPalette },
		{ key = "R", mods = "CTRL", action = wezterm.action.ReloadConfiguration },
		{ key = "R", mods = "SHIFT|CTRL", action = wezterm.action.ReloadConfiguration },
		{ key = "T", mods = "CTRL", action = wezterm.action.SpawnTab("CurrentPaneDomain") },
		{ key = "T", mods = "SHIFT|CTRL", action = wezterm.action.SpawnTab("CurrentPaneDomain") },
		{
			key = "U",
			mods = "CTRL",
			action = wezterm.action.CharSelect({ copy_on_select = true, copy_to = "ClipboardAndPrimarySelection" }),
		},
		{
			key = "U",
			mods = "SHIFT|CTRL",
			action = wezterm.action.CharSelect({ copy_on_select = true, copy_to = "ClipboardAndPrimarySelection" }),
		},
		{ key = "V", mods = "CTRL", action = wezterm.action.PasteFrom("Clipboard") },
		{ key = "V", mods = "SHIFT|CTRL", action = wezterm.action.PasteFrom("Clipboard") },
		{ key = "W", mods = "CTRL", action = wezterm.action.CloseCurrentTab({ confirm = true }) },
		{ key = "W", mods = "SHIFT|CTRL", action = wezterm.action.CloseCurrentTab({ confirm = true }) },
		{ key = "X", mods = "CTRL", action = wezterm.action.ActivateCopyMode },
		{ key = "X", mods = "SHIFT|CTRL", action = wezterm.action.ActivateCopyMode },
		{ key = "Z", mods = "CTRL", action = wezterm.action.TogglePaneZoomState },
		{ key = "Z", mods = "SHIFT|CTRL", action = wezterm.action.TogglePaneZoomState },
		{ key = "[", mods = "SHIFT|SUPER", action = wezterm.action.ActivateTabRelative(-1) },
		{ key = "]", mods = "SHIFT|SUPER", action = wezterm.action.ActivateTabRelative(1) },
		{ key = "^", mods = "CTRL", action = wezterm.action.ActivateTab(5) },
		{ key = "^", mods = "SHIFT|CTRL", action = wezterm.action.ActivateTab(5) },
		{ key = "_", mods = "CTRL", action = wezterm.action.DecreaseFontSize },
		{ key = "_", mods = "SHIFT|CTRL", action = wezterm.action.DecreaseFontSize },
		-- { key = 'c', mods = 'SHIFT|CTRL', action =wezterm.action.CopyTo 'Clipboard' },
		-- { key = "c", mods = "CTRL", action = wezterm.action.CopyTo("Clipboard") },
    { key = "c", mods = "CTRL", action = wezterm.action.SendKey { key = "C", mods = "CTRL" } },
    { key = "n", mods = "CTRL", action = wezterm.action.SendKey { key = "n", mods = "CTRL" } },
		{ key = "c", mods = "SUPER", action = wezterm.action.CopyTo("Clipboard") },
		{ key = "f", mods = "SHIFT|CTRL", action = wezterm.action.Search("CurrentSelectionOrEmptyString") },
		{ key = "f", mods = "SUPER", action = wezterm.action.Search("CurrentSelectionOrEmptyString") },
		{ key = "k", mods = "SHIFT|CTRL", action = wezterm.action.ClearScrollback("ScrollbackOnly") },
		{ key = "k", mods = "SUPER", action = wezterm.action.ClearScrollback("ScrollbackOnly") },
		{ key = "l", mods = "SHIFT|CTRL", action = wezterm.action.ShowDebugOverlay },
		{ key = "m", mods = "SHIFT|CTRL", action = wezterm.action.Hide },
		{ key = "m", mods = "SUPER", action = wezterm.action.Hide },
		{ key = "n", mods = "SHIFT|CTRL", action = wezterm.action.SpawnWindow },
		{ key = "n", mods = "SUPER", action = wezterm.action.SpawnWindow },
		{ key = "p", mods = "SHIFT|CTRL", action = wezterm.action.ActivateCommandPalette },
		{ key = "r", mods = "SHIFT|CTRL", action = wezterm.action.ReloadConfiguration },
		{ key = "r", mods = "SUPER", action = wezterm.action.ReloadConfiguration },
		{ key = "t", mods = "SHIFT|CTRL", action = wezterm.action.SpawnTab("CurrentPaneDomain") },
		{ key = "t", mods = "SUPER", action = wezterm.action.SpawnTab("CurrentPaneDomain") },
		{
			key = "u",
			mods = "SHIFT|CTRL",
			action = wezterm.action.CharSelect({ copy_on_select = true, copy_to = "ClipboardAndPrimarySelection" }),
		},
		-- { key = 'v', mods = 'SHIFT|CTRL', action =wezterm.action.PasteFrom 'Clipboard' },
		{ key = "v", mods = "CTRL", action = wezterm.action.PasteFrom("Clipboard") },
		{ key = "v", mods = "SUPER", action = wezterm.action.PasteFrom("Clipboard") },
		{ key = "w", mods = "SHIFT|CTRL", action = wezterm.action.CloseCurrentTab({ confirm = true }) },
		{ key = "w", mods = "SUPER", action = wezterm.action.CloseCurrentTab({ confirm = true }) },
		{ key = "x", mods = "SHIFT|CTRL", action = wezterm.action.ActivateCopyMode },
		{ key = "z", mods = "SHIFT|CTRL", action = wezterm.action.TogglePaneZoomState },
		{ key = "{", mods = "SUPER", action = wezterm.action.ActivateTabRelative(-1) },
		{ key = "{", mods = "SHIFT|SUPER", action = wezterm.action.ActivateTabRelative(-1) },
		{ key = "}", mods = "SUPER", action = wezterm.action.ActivateTabRelative(1) },
		{ key = "}", mods = "SHIFT|SUPER", action = wezterm.action.ActivateTabRelative(1) },
		{ key = "phys:Space", mods = "SHIFT|CTRL", action = wezterm.action.QuickSelect },
		{ key = "PageUp", mods = "SHIFT", action = wezterm.action.ScrollByPage(-1) },
		{ key = "PageUp", mods = "CTRL", action = wezterm.action.ActivateTabRelative(-1) },
		{ key = "PageUp", mods = "SHIFT|CTRL", action = wezterm.action.MoveTabRelative(-1) },
		{ key = "PageDown", mods = "SHIFT", action = wezterm.action.ScrollByPage(1) },
		{ key = "PageDown", mods = "CTRL", action = wezterm.action.ActivateTabRelative(1) },
		{ key = "PageDown", mods = "SHIFT|CTRL", action = wezterm.action.MoveTabRelative(1) },
		{ key = "LeftArrow", mods = "SHIFT|CTRL", action = wezterm.action.ActivatePaneDirection("Left") },
		{ key = "LeftArrow", mods = "SHIFT|ALT|CTRL", action = wezterm.action.AdjustPaneSize({ "Left", 1 }) },
		{ key = "RightArrow", mods = "SHIFT|CTRL", action = wezterm.action.ActivatePaneDirection("Right") },
		{ key = "RightArrow", mods = "SHIFT|ALT|CTRL", action = wezterm.action.AdjustPaneSize({ "Right", 1 }) },
		{ key = "UpArrow", mods = "SHIFT|CTRL", action = wezterm.action.ActivatePaneDirection("Up") },
		{ key = "UpArrow", mods = "SHIFT|ALT|CTRL", action = wezterm.action.AdjustPaneSize({ "Up", 1 }) },
		{ key = "DownArrow", mods = "SHIFT|CTRL", action = wezterm.action.ActivatePaneDirection("Down") },
		{ key = "DownArrow", mods = "SHIFT|ALT|CTRL", action = wezterm.action.AdjustPaneSize({ "Down", 1 }) },
		{ key = "Insert", mods = "SHIFT", action = wezterm.action.PasteFrom("PrimarySelection") },
		{ key = "Insert", mods = "CTRL", action = wezterm.action.CopyTo("PrimarySelection") },
		{ key = "Copy", mods = "NONE", action = wezterm.action.CopyTo("Clipboard") },
		{ key = "Paste", mods = "NONE", action = wezterm.action.PasteFrom("Clipboard") },
	},

	key_tables = {
		copy_mode = {
			{ key = "Tab", mods = "NONE", action = wezterm.action.CopyMode("MoveForwardWord") },
			{ key = "Tab", mods = "SHIFT", action = wezterm.action.CopyMode("MoveBackwardWord") },
			{ key = "Enter", mods = "NONE", action = wezterm.action.CopyMode("MoveToStartOfNextLine") },
			{ key = "Escape", mods = "NONE", action = wezterm.action.CopyMode("Close") },
			{ key = "Space", mods = "NONE", action = wezterm.action.CopyMode({ SetSelectionMode = "Cell" }) },
			{ key = "$", mods = "NONE", action = wezterm.action.CopyMode("MoveToEndOfLineContent") },
			{ key = "$", mods = "SHIFT", action = wezterm.action.CopyMode("MoveToEndOfLineContent") },
			{ key = ",", mods = "NONE", action = wezterm.action.CopyMode("JumpReverse") },
			{ key = "0", mods = "NONE", action = wezterm.action.CopyMode("MoveToStartOfLine") },
			{ key = ";", mods = "NONE", action = wezterm.action.CopyMode("JumpAgain") },
			{ key = "F", mods = "NONE", action = wezterm.action.CopyMode({ JumpBackward = { prev_char = false } }) },
			{ key = "F", mods = "SHIFT", action = wezterm.action.CopyMode({ JumpBackward = { prev_char = false } }) },
			{ key = "G", mods = "NONE", action = wezterm.action.CopyMode("MoveToScrollbackBottom") },
			{ key = "G", mods = "SHIFT", action = wezterm.action.CopyMode("MoveToScrollbackBottom") },
			{ key = "H", mods = "NONE", action = wezterm.action.CopyMode("MoveToViewportTop") },
			{ key = "H", mods = "SHIFT", action = wezterm.action.CopyMode("MoveToViewportTop") },
			{ key = "L", mods = "NONE", action = wezterm.action.CopyMode("MoveToViewportBottom") },
			{ key = "L", mods = "SHIFT", action = wezterm.action.CopyMode("MoveToViewportBottom") },
			{ key = "M", mods = "NONE", action = wezterm.action.CopyMode("MoveToViewportMiddle") },
			{ key = "M", mods = "SHIFT", action = wezterm.action.CopyMode("MoveToViewportMiddle") },
			{ key = "O", mods = "NONE", action = wezterm.action.CopyMode("MoveToSelectionOtherEndHoriz") },
			{ key = "O", mods = "SHIFT", action = wezterm.action.CopyMode("MoveToSelectionOtherEndHoriz") },
			{ key = "T", mods = "NONE", action = wezterm.action.CopyMode({ JumpBackward = { prev_char = true } }) },
			{ key = "T", mods = "SHIFT", action = wezterm.action.CopyMode({ JumpBackward = { prev_char = true } }) },
			{ key = "V", mods = "NONE", action = wezterm.action.CopyMode({ SetSelectionMode = "Line" }) },
			{ key = "V", mods = "SHIFT", action = wezterm.action.CopyMode({ SetSelectionMode = "Line" }) },
			{ key = "^", mods = "NONE", action = wezterm.action.CopyMode("MoveToStartOfLineContent") },
			{ key = "^", mods = "SHIFT", action = wezterm.action.CopyMode("MoveToStartOfLineContent") },
			{ key = "b", mods = "NONE", action = wezterm.action.CopyMode("MoveBackwardWord") },
			{ key = "b", mods = "ALT", action = wezterm.action.CopyMode("MoveBackwardWord") },
			{ key = "b", mods = "CTRL", action = wezterm.action.CopyMode("PageUp") },
			{ key = "c", mods = "CTRL", action = wezterm.action.CopyMode("Close") },
			{ key = "d", mods = "CTRL", action = wezterm.action.CopyMode({ MoveByPage = 0.5 }) },
			{ key = "e", mods = "NONE", action = wezterm.action.CopyMode("MoveForwardWordEnd") },
			{ key = "f", mods = "NONE", action = wezterm.action.CopyMode({ JumpForward = { prev_char = false } }) },
			{ key = "f", mods = "ALT", action = wezterm.action.CopyMode("MoveForwardWord") },
			{ key = "f", mods = "CTRL", action = wezterm.action.CopyMode("PageDown") },
			{ key = "g", mods = "NONE", action = wezterm.action.CopyMode("MoveToScrollbackTop") },
			{ key = "g", mods = "CTRL", action = wezterm.action.CopyMode("Close") },
			{ key = "h", mods = "NONE", action = wezterm.action.CopyMode("MoveLeft") },
			{ key = "j", mods = "NONE", action = wezterm.action.CopyMode("MoveDown") },
			{ key = "k", mods = "NONE", action = wezterm.action.CopyMode("MoveUp") },
			{ key = "l", mods = "NONE", action = wezterm.action.CopyMode("MoveRight") },
			{ key = "m", mods = "ALT", action = wezterm.action.CopyMode("MoveToStartOfLineContent") },
			{ key = "o", mods = "NONE", action = wezterm.action.CopyMode("MoveToSelectionOtherEnd") },
			{ key = "q", mods = "NONE", action = wezterm.action.CopyMode("Close") },
			{ key = "t", mods = "NONE", action = wezterm.action.CopyMode({ JumpForward = { prev_char = true } }) },
			{ key = "u", mods = "CTRL", action = wezterm.action.CopyMode({ MoveByPage = -0.5 }) },
			{ key = "v", mods = "NONE", action = wezterm.action.CopyMode({ SetSelectionMode = "Cell" }) },
			{ key = "v", mods = "CTRL", action = wezterm.action.CopyMode({ SetSelectionMode = "Block" }) },
			{ key = "w", mods = "NONE", action = wezterm.action.CopyMode("MoveForwardWord") },
			{
				key = "y",
				mods = "NONE",
				action = wezterm.action.Multiple({
					{ CopyTo = "ClipboardAndPrimarySelection" },
					{ CopyMode = "Close" },
				}),
			},
			{ key = "PageUp", mods = "NONE", action = wezterm.action.CopyMode("PageUp") },
			{ key = "PageDown", mods = "NONE", action = wezterm.action.CopyMode("PageDown") },
			{ key = "End", mods = "NONE", action = wezterm.action.CopyMode("MoveToEndOfLineContent") },
			{ key = "Home", mods = "NONE", action = wezterm.action.CopyMode("MoveToStartOfLine") },
			{ key = "LeftArrow", mods = "NONE", action = wezterm.action.CopyMode("MoveLeft") },
			{ key = "LeftArrow", mods = "ALT", action = wezterm.action.CopyMode("MoveBackwardWord") },
			{ key = "RightArrow", mods = "NONE", action = wezterm.action.CopyMode("MoveRight") },
			{ key = "RightArrow", mods = "ALT", action = wezterm.action.CopyMode("MoveForwardWord") },
			{ key = "UpArrow", mods = "NONE", action = wezterm.action.CopyMode("MoveUp") },
			{ key = "DownArrow", mods = "NONE", action = wezterm.action.CopyMode("MoveDown") },
		},

		search_mode = {
			{ key = "Enter", mods = "NONE", action = wezterm.action.CopyMode("PriorMatch") },
			{ key = "Escape", mods = "NONE", action = wezterm.action.CopyMode("Close") },
			{ key = "n", mods = "CTRL", action = wezterm.action.CopyMode("NextMatch") },
			{ key = "p", mods = "CTRL", action = wezterm.action.CopyMode("PriorMatch") },
			{ key = "r", mods = "CTRL", action = wezterm.action.CopyMode("CycleMatchType") },
			{ key = "u", mods = "CTRL", action = wezterm.action.CopyMode("ClearPattern") },
			{ key = "PageUp", mods = "NONE", action = wezterm.action.CopyMode("PriorMatchPage") },
			{ key = "PageDown", mods = "NONE", action = wezterm.action.CopyMode("NextMatchPage") },
			{ key = "UpArrow", mods = "NONE", action = wezterm.action.CopyMode("PriorMatch") },
			{ key = "DownArrow", mods = "NONE", action = wezterm.action.CopyMode("NextMatch") },
		},
	},
}

-- Leader is the same as my old tmux prefix


